import {
  stageTaskActionBindings,
  stageTaskDefinitions,
  stageTaskFormBindings,
  workflowActionDefinitions,
  workflowDefinitionVersions,
  workflowDefinitions,
  workflowStageDefinitions,
  workflowTransitionDefinitions,
} from "./workflow.schema";
import {
  workflowStageJoinPredecessors,
  workflowTransitionTargets,
} from "./workflow-parallel.schema";

export const workflowGraphSelection = {
  definition: {
    active: workflowDefinitions.active,
    id: workflowDefinitions.id,
    code: workflowDefinitions.code,
    name: workflowDefinitions.name,
    description: workflowDefinitions.description,
  },
  version: {
    id: workflowDefinitionVersions.id,
    versionNumber: workflowDefinitionVersions.versionNumber,
    metadata: workflowDefinitionVersions.metadata,
    status: workflowDefinitionVersions.status,
    rowVersion: workflowDefinitionVersions.rowVersion,
    createdAt: workflowDefinitionVersions.createdAt,
    publishedAt: workflowDefinitionVersions.publishedAt,
    retiredAt: workflowDefinitionVersions.retiredAt,
  },
  stage: {
    id: workflowStageDefinitions.id,
    stableKey: workflowStageDefinitions.code,
    name: workflowStageDefinitions.name,
    description: workflowStageDefinitions.description,
    enabled: workflowStageDefinitions.enabled,
    optional: workflowStageDefinitions.optional,
    displayOrder: workflowStageDefinitions.sequence,
    initial: workflowStageDefinitions.initial,
    publicStatus: workflowStageDefinitions.applicantStatus,
    publicLabel: workflowStageDefinitions.applicantLabel,
    publicDescription: workflowStageDefinitions.applicantDescription,
    repeatable: workflowStageDefinitions.repeatable,
    allowApplicantWithdrawal: workflowStageDefinitions.allowApplicantWithdrawal,
    coiGated: workflowStageDefinitions.coiGated,
    coiFormVersionId: workflowStageDefinitions.coiFormVersionId,
    slaHours: workflowStageDefinitions.slaHours,
    entryCondition: workflowStageDefinitions.entryCondition,
    exitCondition: workflowStageDefinitions.exitCondition,
  },
  action: {
    stageId: workflowActionDefinitions.stageId,
    id: workflowActionDefinitions.id,
    stableKey: workflowActionDefinitions.stableKey,
    label: workflowActionDefinitions.label,
    actionType: workflowActionDefinitions.actionType,
    condition: workflowActionDefinitions.condition,
    configuration: workflowActionDefinitions.configuration,
    enabled: workflowActionDefinitions.enabled,
    reasonRequired: workflowActionDefinitions.reasonRequired,
    displayOrder: workflowActionDefinitions.displayOrder,
  },
  task: {
    stageId: stageTaskDefinitions.stageId,
    id: stageTaskDefinitions.id,
    stableKey: stageTaskDefinitions.stableKey,
    name: stageTaskDefinitions.name,
    description: stageTaskDefinitions.description,
    displayOrder: stageTaskDefinitions.displayOrder,
    required: stageTaskDefinitions.required,
    roleId: stageTaskDefinitions.roleId,
    namedUserOverrideId: stageTaskDefinitions.namedUserOverrideId,
    assignmentMode: stageTaskDefinitions.assignmentMode,
    reviewerCount: stageTaskDefinitions.reviewerCount,
    reviewRelease: stageTaskDefinitions.reviewRelease,
    submittedReplacementPolicy: stageTaskDefinitions.submittedReplacementPolicy,
    taskType: stageTaskDefinitions.taskType,
    requiredCompletionCount: stageTaskDefinitions.requiredCompletionCount,
    completionMode: stageTaskDefinitions.completionMode,
    completionPercentage: stageTaskDefinitions.completionPercentage,
    quorum: stageTaskDefinitions.quorum,
    quorumRule: stageTaskDefinitions.quorumRule,
    config: stageTaskDefinitions.config,
    permissions: stageTaskDefinitions.permissions,
  },
  formBinding: {
    contextFields: stageTaskFormBindings.contextFields,
    formVersionId: stageTaskFormBindings.formVersionId,
  },
  taskAction: {
    actionKey: stageTaskActionBindings.actionKey,
    taskDefinitionId: stageTaskActionBindings.taskDefinitionId,
  },
  transition: {
    id: workflowTransitionDefinitions.id,
    fromStageId: workflowTransitionDefinitions.fromStageId,
    actionKey: workflowTransitionDefinitions.actionKey,
    terminalOutcome: workflowTransitionDefinitions.terminalOutcome,
    terminalApplicantStatus:
      workflowTransitionDefinitions.terminalApplicantStatus,
    priority: workflowTransitionDefinitions.priority,
    condition: workflowTransitionDefinitions.condition,
  },
  transitionTarget: {
    transitionId: workflowTransitionTargets.transitionId,
    targetStageId: workflowTransitionTargets.targetStageId,
  },
  joinPredecessor: {
    stageId: workflowStageJoinPredecessors.stageId,
    predecessorStageId: workflowStageJoinPredecessors.predecessorStageId,
  },
};
