import type { WorkflowProgressView } from "@/modules/workflows/api/WorkflowProgressTypes";
import { referenceWorkflow } from "./ReferenceWorkflowFixture";

export const workflowProgressFixture: WorkflowProgressView = {
  completedAt: null,
  graph: {
    stages: referenceWorkflow.stages.slice(0, 2).map((stage, index) => ({
      ...stage,
      stableKey: index === 0 ? "eligibility" : "technical",
      name: index === 0 ? "Eligibility" : "Technical Assessment",
    })),
    transitions: [
      {
        id: "proceed-route",
        actionKey: "PROCEED",
        sourceStageKey: "eligibility",
        targetStageKeys: ["technical"],
        terminalOutcome: null,
        condition: null,
        priority: 1,
      },
    ],
  },
  id: "workflow-one",
  name: "SME Fund Funding Workflow",
  stages: [
    {
      activatedAt: "2026-09-20T08:00:00.000Z",
      completedAt: "2026-09-20T10:00:00.000Z",
      description: "Check the application.",
      id: "stage-one",
      iterationNumber: 1,
      name: "Eligibility",
      sequence: 1,
      stableKey: "eligibility",
      status: "COMPLETED",
      tasks: [],
    },
    {
      activatedAt: "2026-09-21T08:00:00.000Z",
      completedAt: null,
      description: "Assess the proposal.",
      id: "stage-two",
      iterationNumber: 1,
      name: "Technical Assessment",
      sequence: 2,
      stableKey: "technical",
      status: "ACTIVE",
      tasks: [
        {
          actionedAt: null,
          assignedRoleName: "Sector Specialist",
          assignedUserEmail: "reviewer@example.test",
          assignedUserName: "Reviewer",
          canOpen: true,
          dueAt: "2026-09-29T08:09:00.000Z",
          id: "task-one",
          name: "Review proposal",
          required: true,
          status: "IN_PROGRESS",
          taskType: "CONTRIBUTING",
        },
        {
          actionedAt: null,
          assignedRoleName: "Programme Officer",
          assignedUserEmail: null,
          assignedUserName: null,
          canOpen: false,
          dueAt: null,
          id: "task-two",
          name: "Assessment decision",
          required: true,
          status: "PENDING",
          taskType: "STAGE_DECISION",
        },
      ],
    },
  ],
  startedAt: "2026-09-20T08:00:00.000Z",
  status: "ACTIVE",
  terminalOutcome: null,
  takenPaths: [{ transitionId: "proceed-route", targetStageKey: "technical" }],
  versionNumber: 2,
};
