import { cn } from "@/lib/utils";

const theme = [
  "[--nav-width:320px]",
  "[--app-header-height:64px]",
  "max-[768px]:[--app-header-height:64px]",
  "[--theme-elevation-0:var(--sme-brand-white)]",
  "[--theme-elevation-50:#f9fafb]",
  "[--theme-elevation-100:#f3f5f8]",
  "[--theme-elevation-150:#e8ecf2]",
  "[--theme-elevation-200:#dce2ea]",
  "[--theme-text:var(--sme-brand-navy)]",
  "[--theme-success-500:var(--sme-brand-green)]",
  "[--font-body:Arial,Helvetica,sans-serif]",
  "[&_body]:bg-brand-white",
  "[&_body]:text-brand-navy",
];

const shell = [
  "[&_.nav]:border-0",
  "[&_.nav]:bg-brand-navy",
  "[&_.nav]:text-brand-white",
  String.raw`[&_.nav\_\_scroll]:p-0`,
  String.raw`[&_.nav\_\_scroll]:overflow-hidden`,
  String.raw`[&:has(.nav--nav-open_.cms-sidebar)_.template-default\_\_nav-toggler-wrapper]:hidden`,
  "[&_.template-default]:[--nav-width:var(--cms-nav-width,320px)]",
  "max-[1024px]:[&_.template-default]:[--nav-width:min(21rem,90vw)]",
  "[&_.app-header]:border-b",
  "[&_.app-header]:border-solid",
  "[&_.app-header]:border-brand-navy/10",
  "[&_.app-header]:bg-brand-white",
  String.raw`[&_.app-header\_\_content]:px-[32px]`,
  String.raw`max-[768px]:[&_.app-header\_\_content]:px-[16px]`,
  // Payload renders Edit first; hide it above the focused page editors.
  String.raw`[&_.template-default\_\_wrap:has(.collection-edit--pages_#about-content)>.doc-header_.doc-tab:first-child]:hidden`,
  String.raw`[&_.template-default\_\_wrap:has(.collection-edit--pages_#how-to-apply-content)>.doc-header_.doc-tab:first-child]:hidden`,
  String.raw`[&_.template-default\_\_wrap:has(.collection-edit--pages_#funding-overview)>.doc-header_.doc-tab:first-child]:hidden`,
  String.raw`[&_.template-default\_\_wrap:has(.collection-edit--pages_#faq-content)>.doc-header_.doc-tab:first-child]:hidden`,
  "[&_.card]:border",
  "[&_.card]:border-solid",
  "[&_.card]:border-[var(--theme-elevation-200)]",
  "[&_.card]:rounded-[16px]",
  "[&_.card]:shadow-sm",
  "[&_.btn--style-primary]:text-brand-white",
  "[&_.btn--style-primary]:bg-brand-navy",
  "[&_.btn--style-primary]:border-brand-navy",
  "[&_.btn--style-primary:hover]:bg-brand-orange",
  "[&_.btn--style-primary:hover]:border-brand-orange",
];

// The HTML root also contains Payload's portal, so these utilities reach its
// native media drawer without replacing its upload tools or focus handling.
const mediaDrawer = [
  String.raw`[&_.doc-drawer[id^=doc-drawer\_media\_]]:[--gutter-h:24px]`,
  String.raw`max-[640px]:[&_.doc-drawer[id^=doc-drawer\_media\_]]:[--gutter-h:16px]`,
  String.raw`[&_.doc-drawer[id^=doc-drawer\_media\_]]:[--doc-controls-height:64px]`,
  String.raw`[&_.doc-drawer[id^=doc-drawer\_media\_]]:items-stretch`,
  String.raw`[&_.doc-drawer[id^=doc-drawer\_media\_]]:h-dvh`,
  String.raw`[&_.doc-drawer[id^=doc-drawer\_media\_]]:p-0`,
  String.raw`[&_.doc-drawer[id^=doc-drawer\_media\_]_.drawer\_\_content]:box-border`,
  String.raw`[&_.doc-drawer[id^=doc-drawer\_media\_]_.drawer\_\_content]:shrink-0`,
  String.raw`[&_.doc-drawer[id^=doc-drawer\_media\_]_.drawer\_\_content]:w-[min(42rem,100vw)]`,
  String.raw`[&_.doc-drawer[id^=doc-drawer\_media\_]_.drawer\_\_content]:h-dvh`,
  String.raw`[&_.doc-drawer[id^=doc-drawer\_media\_]_.drawer\_\_content]:max-h-dvh`,
  String.raw`[&_.doc-drawer[id^=doc-drawer\_media\_]_.drawer\_\_content]:border-0`,
  String.raw`[&_.doc-drawer[id^=doc-drawer\_media\_]_.drawer\_\_content]:border-l`,
  String.raw`[&_.doc-drawer[id^=doc-drawer\_media\_]_.drawer\_\_content]:border-solid`,
  String.raw`[&_.doc-drawer[id^=doc-drawer\_media\_]_.drawer\_\_content]:border-brand-navy/15`,
  String.raw`[&_.doc-drawer[id^=doc-drawer\_media\_]_.drawer\_\_content]:border-t-[4px]`,
  String.raw`[&_.doc-drawer[id^=doc-drawer\_media\_]_.drawer\_\_content]:border-t-brand-orange`,
  String.raw`[&_.doc-drawer[id^=doc-drawer\_media\_]_.drawer\_\_content]:rounded-none`,
  String.raw`[&_.doc-drawer[id^=doc-drawer\_media\_]_.drawer\_\_content]:bg-brand-white`,
  String.raw`[&_.doc-drawer[id^=doc-drawer\_media\_]_.drawer\_\_content]:shadow-2xl`,
  String.raw`[&_.doc-drawer[id^=doc-drawer\_media\_]_.drawer\_\_content-children]:h-full`,
  String.raw`[&_.doc-drawer[id^=doc-drawer\_media\_]_.drawer\_\_content-children]:max-h-full`,
  String.raw`[&_.doc-drawer[id^=doc-drawer\_media\_]_.doc-drawer\_\_header]:mt-[24px]`,
  String.raw`[&_.doc-drawer[id^=doc-drawer\_media\_]_.doc-drawer\_\_header]:border-brand-navy/10`,
  String.raw`[&_.doc-drawer[id^=doc-drawer\_media\_]_.doc-drawer\_\_header-text]:text-brand-navy`,
  String.raw`[&_.doc-drawer[id^=doc-drawer\_media\_]_.doc-drawer\_\_header-text]:text-[24px]`,
  String.raw`[&_.doc-drawer[id^=doc-drawer\_media\_]_.doc-drawer\_\_header-text]:font-bold`,
  String.raw`[&_.doc-drawer[id^=doc-drawer\_media\_]_.doc-controls]:bg-brand-white`,
  String.raw`[&_.doc-drawer[id^=doc-drawer\_media\_]_.doc-controls\_\_wrapper]:h-auto`,
  String.raw`[&_.doc-drawer[id^=doc-drawer\_media\_]_.doc-controls\_\_wrapper]:min-h-[64px]`,
  String.raw`[&_.doc-drawer[id^=doc-drawer\_media\_]_.doc-controls\_\_wrapper]:gap-[12px]`,
  String.raw`[&_.doc-drawer[id^=doc-drawer\_media\_]_.doc-controls\_\_meta]:flex-wrap`,
  String.raw`[&_.doc-drawer[id^=doc-drawer\_media\_]_.doc-controls\_\_meta]:gap-x-[12px]`,
  String.raw`[&_.doc-drawer[id^=doc-drawer\_media\_]_.doc-controls\_\_meta]:gap-y-[4px]`,
  String.raw`[&_.doc-drawer[id^=doc-drawer\_media\_]_.file-details]:border-brand-navy/15`,
  String.raw`[&_.doc-drawer[id^=doc-drawer\_media\_]_.file-details]:rounded-[12px]`,
  String.raw`[&_.doc-drawer[id^=doc-drawer\_media\_]_.file-details]:bg-brand-navy/3`,
  String.raw`[&_.doc-drawer[id^=doc-drawer\_media\_]_.file-details]:shadow-none`,
  String.raw`[&_.doc-drawer[id^=doc-drawer\_media\_]_.file-details\_\_edit]:rounded-full`,
  String.raw`[&_.doc-drawer[id^=doc-drawer\_media\_]_.file-details\_\_edit]:px-[12px]`,
  String.raw`[&_.doc-drawer[id^=doc-drawer\_media\_]_.file-details\_\_edit]:py-[6px]`,
  String.raw`[&_.doc-drawer[id^=doc-drawer\_media\_]_.file-details\_\_edit]:text-brand-navy`,
  String.raw`[&_.doc-drawer[id^=doc-drawer\_media\_]_.file-details\_\_edit]:bg-brand-gold`,
  String.raw`[&_.doc-drawer[id^=doc-drawer\_media\_]_.file-details\_\_edit]:font-semibold`,
];

export const cmsAdminClassName = cn(theme, shell, mediaDrawer);
