import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Building2, CheckCircle2, ClipboardCheck, FileText, Send, UserRound } from "lucide-react";
import { Button } from "@/components/ui/button";

export const metadata: Metadata = { title: "How to apply" };
const documents = ["BIPA proof of business registration", "NAMRA Good Standing Certificate", "Social Security Commission Good Standing Certificate", "Valid MSME Certificate", "Police Clearance Certificate or proof of application", "Business bank confirmation letter or bank statement", "Business profile (maximum 5 pages)", "Business pitch deck (maximum 12 slides)"];

export default function HowToApplyPage() {
  const steps = [{icon:ClipboardCheck,t:"Check eligibility",d:"Confirm the mandatory ownership, registration and operating requirements."},{icon:FileText,t:"Prepare documents",d:"Collect current, legible PDF copies of the supporting documents."},{icon:UserRound,t:"Tell us about you",d:"Provide applicant and contact information."},{icon:Building2,t:"Describe your business",d:"Show what the business does, who it serves and how it is growing."},{icon:Send,t:"Review and submit",d:"Accept the declaration and keep the application reference."}];
  return <><section className="bg-navy py-20 text-white"><div className="container max-w-4xl text-center"><p className="eyebrow text-orange">A guided application</p><h1 className="display mt-4 text-5xl font-semibold sm:text-6xl">Know what you need before you begin.</h1><p className="mx-auto mt-6 max-w-2xl text-lg leading-8 text-white/65">Follow five clear steps and prepare your supporting documents in advance.</p></div></section>
  <section className="section bg-white"><div className="container"><div className="grid gap-4 md:grid-cols-5">{steps.map(({icon:Icon,t,d},i)=><article key={t} className="relative rounded-2xl border border-slate-200 p-5"><span className="absolute right-4 top-4 text-xs font-extrabold text-slate-300">0{i+1}</span><Icon className="size-6 text-orange"/><h2 className="mt-5 font-bold text-navy">{t}</h2><p className="mt-2 text-xs leading-5 text-slate-500">{d}</p></article>)}</div></div></section>
  <section className="section bg-slate-50"><div className="container grid gap-12 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">Document checklist</p><h2 className="display mt-3 text-4xl font-semibold text-navy">Prepare clear, current PDFs</h2><p className="mt-5 text-sm leading-6 text-slate-600">Some documents expire. Check that certificates are valid and that every page is legible before uploading.</p><div className="mt-6 rounded-2xl border border-gold/30 bg-gold/10 p-5 text-sm text-slate-700"><strong className="text-navy">Demo note:</strong> Files selected in this prototype are not uploaded or stored.</div></div><ul className="card grid gap-1 p-5 sm:grid-cols-2">{documents.map(d=><li key={d} className="flex gap-3 rounded-xl p-3 text-sm text-slate-700"><CheckCircle2 className="mt-0.5 size-5 shrink-0 text-orange"/>{d}</li>)}</ul></div></section>
  <section className="bg-orange-pale py-14"><div className="container flex flex-col items-start justify-between gap-6 sm:flex-row sm:items-center"><div><h2 className="display text-3xl font-semibold text-navy">Ready to get started?</h2><p className="mt-2 text-sm text-slate-600">Complete the eligibility check first—it takes about two minutes.</p></div><div className="flex gap-3"><Button asChild variant="outline"><Link href="/eligibility">Check eligibility</Link></Button><Button asChild><Link href="/apply">Start application <ArrowRight className="size-4"/></Link></Button></div></div></section></>;
}
