import type { Metadata } from "next";
import Link from "next/link";
import { ArrowRight, Banknote, Check, Globe2, HeartHandshake, Lightbulb, Target, Users } from "lucide-react";
import { Button } from "@/components/ui/button";

export const metadata: Metadata = { title: "Funding opportunity" };

const uses = ["Equipment and productive assets", "Market expansion and export readiness", "Product or service innovation", "Business systems and operational improvements", "Activities that support sustainable job creation"];

export default function FundingPage() {
  return <>
    <section className="bg-navy py-20 text-white"><div className="container grid gap-12 lg:grid-cols-[1fr_360px] lg:items-end"><div><p className="eyebrow text-orange">SME Growth Grant</p><h1 className="display mt-4 max-w-3xl text-5xl font-semibold sm:text-6xl">Funding to move your business forward.</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/65">Targeted grants and practical enterprise support for established Namibian SMEs with a feasible model, real traction and the ambition to grow.</p></div><div className="rounded-3xl border border-white/15 bg-white/8 p-7"><p className="text-sm text-white/55">Available grant</p><p className="mt-2 text-4xl font-black text-gold">N$50,000</p><p className="text-lg font-semibold">to N$100,000</p><Button asChild variant="gold" className="mt-6 w-full"><Link href="/eligibility">Check eligibility <ArrowRight className="size-4" /></Link></Button></div></div></section>
    <section className="section bg-white"><div className="container grid gap-12 lg:grid-cols-2"><div><p className="eyebrow">What the fund supports</p><h2 className="display mt-3 text-4xl font-semibold text-navy">Investment in sustainable growth</h2><p className="mt-5 leading-7 text-slate-600">Funding is intended to strengthen competitiveness, improve productivity and unlock measurable growth—not simply cover routine operating costs.</p><ul className="mt-7 grid gap-3">{uses.map(x => <li key={x} className="flex gap-3 text-sm text-slate-700"><span className="mt-0.5 grid size-5 shrink-0 place-items-center rounded-full bg-orange-pale"><Check className="size-3 text-navy" /></span>{x}</li>)}</ul></div><div className="grid grid-cols-2 gap-4">{[{icon:Banknote,t:"Grant funding",d:"Growth and expansion capital"},{icon:HeartHandshake,t:"Mentorship",d:"Practical coaching and advice"},{icon:Globe2,t:"Market access",d:"Linkages and export readiness"},{icon:Lightbulb,t:"Innovation",d:"Support to compete and adapt"}].map(({icon:Icon,t,d})=><div className="card p-6" key={t}><Icon className="size-6 text-orange"/><h3 className="mt-4 font-bold text-navy">{t}</h3><p className="mt-2 text-xs leading-5 text-slate-500">{d}</p></div>)}</div></div></section>
    <section className="section bg-slate-50"><div className="container"><div className="max-w-2xl"><p className="eyebrow">Priority applicants</p><h2 className="display mt-3 text-4xl font-semibold text-navy">Built for entrepreneurs creating value</h2></div><div className="mt-10 grid gap-5 md:grid-cols-3">{[{icon:Users,t:"Inclusive ownership",d:"Youth-owned and women-owned enterprises are encouraged to apply."},{icon:Target,t:"Ready to grow",d:"Existing businesses seeking expansion, improvement or access to new markets."},{icon:Lightbulb,t:"Economic impact",d:"Enterprises with the potential to innovate, create employment and diversify the economy."}].map(({icon:Icon,t,d})=><article className="card p-7" key={t}><Icon className="size-7 text-gold-dark"/><h3 className="mt-5 text-lg font-bold text-navy">{t}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{d}</p></article>)}</div></div></section>
    <section className="bg-orange-pale py-14"><div className="container flex flex-col items-start justify-between gap-6 sm:flex-row sm:items-center"><div><h2 className="display text-3xl font-semibold text-navy">Could this be your next step?</h2><p className="mt-2 text-sm text-slate-600">Check all mandatory requirements before applying.</p></div><Button asChild size="lg"><Link href="/eligibility">Check eligibility <ArrowRight className="size-4" /></Link></Button></div></section>
  </>;
}
